# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mailadm/tmp/c-career-test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mailadm/tmp/c-career-test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mailadm/tmp/c-career-test/CMakeFiles /home/mailadm/tmp/c-career-test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mailadm/tmp/c-career-test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named career_test3

# Build rule for target.
career_test3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 career_test3
.PHONY : career_test3

# fast build rule for target.
career_test3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/build
.PHONY : career_test3/fast

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/main.c.s
.PHONY : main.c.s

src/logger.o: src/logger.c.o
.PHONY : src/logger.o

# target to build an object file
src/logger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/logger.c.o
.PHONY : src/logger.c.o

src/logger.i: src/logger.c.i
.PHONY : src/logger.i

# target to preprocess a source file
src/logger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/logger.c.i
.PHONY : src/logger.c.i

src/logger.s: src/logger.c.s
.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/logger.c.s
.PHONY : src/logger.c.s

src/smtpDispatch.o: src/smtpDispatch.c.o
.PHONY : src/smtpDispatch.o

# target to build an object file
src/smtpDispatch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpDispatch.c.o
.PHONY : src/smtpDispatch.c.o

src/smtpDispatch.i: src/smtpDispatch.c.i
.PHONY : src/smtpDispatch.i

# target to preprocess a source file
src/smtpDispatch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpDispatch.c.i
.PHONY : src/smtpDispatch.c.i

src/smtpDispatch.s: src/smtpDispatch.c.s
.PHONY : src/smtpDispatch.s

# target to generate assembly for a file
src/smtpDispatch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpDispatch.c.s
.PHONY : src/smtpDispatch.c.s

src/smtpItcq.o: src/smtpItcq.c.o
.PHONY : src/smtpItcq.o

# target to build an object file
src/smtpItcq.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpItcq.c.o
.PHONY : src/smtpItcq.c.o

src/smtpItcq.i: src/smtpItcq.c.i
.PHONY : src/smtpItcq.i

# target to preprocess a source file
src/smtpItcq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpItcq.c.i
.PHONY : src/smtpItcq.c.i

src/smtpItcq.s: src/smtpItcq.c.s
.PHONY : src/smtpItcq.s

# target to generate assembly for a file
src/smtpItcq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpItcq.c.s
.PHONY : src/smtpItcq.c.s

src/smtpMailFile.o: src/smtpMailFile.c.o
.PHONY : src/smtpMailFile.o

# target to build an object file
src/smtpMailFile.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpMailFile.c.o
.PHONY : src/smtpMailFile.c.o

src/smtpMailFile.i: src/smtpMailFile.c.i
.PHONY : src/smtpMailFile.i

# target to preprocess a source file
src/smtpMailFile.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpMailFile.c.i
.PHONY : src/smtpMailFile.c.i

src/smtpMailFile.s: src/smtpMailFile.c.s
.PHONY : src/smtpMailFile.s

# target to generate assembly for a file
src/smtpMailFile.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpMailFile.c.s
.PHONY : src/smtpMailFile.c.s

src/smtpSession.o: src/smtpSession.c.o
.PHONY : src/smtpSession.o

# target to build an object file
src/smtpSession.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpSession.c.o
.PHONY : src/smtpSession.c.o

src/smtpSession.i: src/smtpSession.c.i
.PHONY : src/smtpSession.i

# target to preprocess a source file
src/smtpSession.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpSession.c.i
.PHONY : src/smtpSession.c.i

src/smtpSession.s: src/smtpSession.c.s
.PHONY : src/smtpSession.s

# target to generate assembly for a file
src/smtpSession.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpSession.c.s
.PHONY : src/smtpSession.c.s

src/smtpSock.o: src/smtpSock.c.o
.PHONY : src/smtpSock.o

# target to build an object file
src/smtpSock.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpSock.c.o
.PHONY : src/smtpSock.c.o

src/smtpSock.i: src/smtpSock.c.i
.PHONY : src/smtpSock.i

# target to preprocess a source file
src/smtpSock.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpSock.c.i
.PHONY : src/smtpSock.c.i

src/smtpSock.s: src/smtpSock.c.s
.PHONY : src/smtpSock.s

# target to generate assembly for a file
src/smtpSock.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpSock.c.s
.PHONY : src/smtpSock.c.s

src/smtpSvrRecvEpoll.o: src/smtpSvrRecvEpoll.c.o
.PHONY : src/smtpSvrRecvEpoll.o

# target to build an object file
src/smtpSvrRecvEpoll.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpSvrRecvEpoll.c.o
.PHONY : src/smtpSvrRecvEpoll.c.o

src/smtpSvrRecvEpoll.i: src/smtpSvrRecvEpoll.c.i
.PHONY : src/smtpSvrRecvEpoll.i

# target to preprocess a source file
src/smtpSvrRecvEpoll.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpSvrRecvEpoll.c.i
.PHONY : src/smtpSvrRecvEpoll.c.i

src/smtpSvrRecvEpoll.s: src/smtpSvrRecvEpoll.c.s
.PHONY : src/smtpSvrRecvEpoll.s

# target to generate assembly for a file
src/smtpSvrRecvEpoll.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpSvrRecvEpoll.c.s
.PHONY : src/smtpSvrRecvEpoll.c.s

src/smtpSvrRecvFdSet.o: src/smtpSvrRecvFdSet.c.o
.PHONY : src/smtpSvrRecvFdSet.o

# target to build an object file
src/smtpSvrRecvFdSet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpSvrRecvFdSet.c.o
.PHONY : src/smtpSvrRecvFdSet.c.o

src/smtpSvrRecvFdSet.i: src/smtpSvrRecvFdSet.c.i
.PHONY : src/smtpSvrRecvFdSet.i

# target to preprocess a source file
src/smtpSvrRecvFdSet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpSvrRecvFdSet.c.i
.PHONY : src/smtpSvrRecvFdSet.c.i

src/smtpSvrRecvFdSet.s: src/smtpSvrRecvFdSet.c.s
.PHONY : src/smtpSvrRecvFdSet.s

# target to generate assembly for a file
src/smtpSvrRecvFdSet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpSvrRecvFdSet.c.s
.PHONY : src/smtpSvrRecvFdSet.c.s

src/smtpTps.o: src/smtpTps.c.o
.PHONY : src/smtpTps.o

# target to build an object file
src/smtpTps.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpTps.c.o
.PHONY : src/smtpTps.c.o

src/smtpTps.i: src/smtpTps.c.i
.PHONY : src/smtpTps.i

# target to preprocess a source file
src/smtpTps.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpTps.c.i
.PHONY : src/smtpTps.c.i

src/smtpTps.s: src/smtpTps.c.s
.PHONY : src/smtpTps.s

# target to generate assembly for a file
src/smtpTps.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpTps.c.s
.PHONY : src/smtpTps.c.s

src/smtpUtils.o: src/smtpUtils.c.o
.PHONY : src/smtpUtils.o

# target to build an object file
src/smtpUtils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpUtils.c.o
.PHONY : src/smtpUtils.c.o

src/smtpUtils.i: src/smtpUtils.c.i
.PHONY : src/smtpUtils.i

# target to preprocess a source file
src/smtpUtils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpUtils.c.i
.PHONY : src/smtpUtils.c.i

src/smtpUtils.s: src/smtpUtils.c.s
.PHONY : src/smtpUtils.s

# target to generate assembly for a file
src/smtpUtils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/career_test3.dir/build.make CMakeFiles/career_test3.dir/src/smtpUtils.c.s
.PHONY : src/smtpUtils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... career_test3"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/smtpDispatch.o"
	@echo "... src/smtpDispatch.i"
	@echo "... src/smtpDispatch.s"
	@echo "... src/smtpItcq.o"
	@echo "... src/smtpItcq.i"
	@echo "... src/smtpItcq.s"
	@echo "... src/smtpMailFile.o"
	@echo "... src/smtpMailFile.i"
	@echo "... src/smtpMailFile.s"
	@echo "... src/smtpSession.o"
	@echo "... src/smtpSession.i"
	@echo "... src/smtpSession.s"
	@echo "... src/smtpSock.o"
	@echo "... src/smtpSock.i"
	@echo "... src/smtpSock.s"
	@echo "... src/smtpSvrRecvEpoll.o"
	@echo "... src/smtpSvrRecvEpoll.i"
	@echo "... src/smtpSvrRecvEpoll.s"
	@echo "... src/smtpSvrRecvFdSet.o"
	@echo "... src/smtpSvrRecvFdSet.i"
	@echo "... src/smtpSvrRecvFdSet.s"
	@echo "... src/smtpTps.o"
	@echo "... src/smtpTps.i"
	@echo "... src/smtpTps.s"
	@echo "... src/smtpUtils.o"
	@echo "... src/smtpUtils.i"
	@echo "... src/smtpUtils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

